name: Build Verify Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_wheels:
    name: Build whl on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # windows-latest is an Intel runner
        # macos-13 is an Intel runner, macos-latest is an Apple Silicon runner
        # ubuntu-latest is an Intel runner, ubuntu-24.04-arm is an arm runner
        os: 
          - windows-latest
          - macos-13
          - macos-latest
          # - ubuntu-latest
          - ubuntu-24.04-arm
      fail-fast: false
    steps:
      - name: Install Hatch
        uses: pypa/hatch@install
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - uses: actions/checkout@v4
      - name: compile deno binaries
        run: |
          mkdir dist
          deno compile -ERNW -o dist/bids-validator jsr:@bids/validator
      - name: Build wheel
        run: hatch build -t wheel
      - uses: actions/upload-artifact@v4
        with:
          name: bids-validator-${{ matrix.os }}
          path: |
            dist/bids-validator
            dist/bids-validator.*
      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.os }}
          path: dist/*.whl
      - name: print out the content of the dist folder
        run: ls -l dist/
      - name: Publish wheels
        run: hatch publish -r test
        env:
          HATCH_INDEX_USER: ${{ secrets.HATCH_INDEX_USER }}
          HATCH_INDEX_AUTH: ${{ secrets.HATCH_INDEX_AUTH }}
